name: Update R6 Stats

on:
  schedule:
    - cron: '0 * * * *' # Spustí se každou hodinu
  workflow_dispatch: # Umožní ti spustit bota ručně

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Aktualizováno z v3 na v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Aktualizováno z v4 na v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        run: python update_stats.py

      - name: Commit and push changes
        run: |
          git config --global user.name "PellarBot"
          git config --global user.email "bot@pellarhodon.com"
          git add index.html
          git commit -m "SYSTEM: R6_DATABASE_SYNC_COMPLETE" || exit 0
          git push
